includes:
- configs/water/base.yml

model:
  name: dimenetplusplus
  hidden_channels: 128
  out_emb_channels: 256
  int_emb_size: 64
  basis_emb_size: 8
  num_blocks: 4
  cutoff: 5.0
  envelope_exponent: 5
  num_radial: 6
  num_spherical: 7
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  regress_forces: True
  use_pbc: True
  otf_graph: True

optim:
  loss_force: l2mae
