includes:
- configs/md17/base.yml

model:
  name: dimenet
  hidden_channels: 128
  num_blocks: 6
  cutoff: 5.0
  envelope_exponent: 5
  num_bilinear: 8
  num_spherical: 7
  num_radial: 6
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  regress_forces: True
  use_pbc: False
  otf_graph: True

optim:
  batch_size: 32
  eval_batch_size: 32
  num_workers: 4
  lr_initial: 0.001
  optimizer: AdamW
  optimizer_params: {"eps": 1.e-7, "weight_decay": 0.000002, "amsgrad": True}

  scheduler: ReduceLROnPlateau
  patience: 5
  factor: 0.8
  min_lr: 0.000001

  max_epochs: 10000
  force_coefficient: 1000
  energy_coefficient: 1
  ema_decay: 0.999
  clip_grad_norm: 10
  loss_energy: mae
  loss_force: mae
  
