model_dir: MODELPATH
dataset_src: DATAPATH/water/10k/test
nequip_data_config: configs/simulate/nequip_data_cfg/water.yml
dp_data_path: DATAPATH/water_dp/test
identifier: 500ps
sim_type: ocp
seed: 0
save_freq: 100
steps: 500000
max_test_points: 10000

kcal: False
T_init: 300.
integrator: NoseHoover
integrator_config: {"timestep": 1., "temperature": 300., "ttime": 20.}
